### ISSUE TITLE
Program emits redundant (?) "difficulty" value for Skill Containers and Spell Containers

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs5#2]
Value seems to always be "e"

**Comment by richardwilkes** [comment]
Can you elaborate?

**Comment by rinickolous** [comment]
I opened and saved a `.gcs` file originally created in GCS4 (since "Save As" doesn't seem to be implemented yet). Upon saving, the "skill_container" and "spell_container" type items in the JSON data contain "difficulty" keys with the value "e".

**Comment by richardwilkes** [comment]
Ah... I didn't even notice this was against gcs5. I'll take a look and see if there is something wrong there.

**Comment by richardwilkes** [comment]
Fixed in df3656dc

The issue has to do with the way I share the data structure for containers & non-containers... that field wasn't being properly omitted when saving.

Note: if you're using the current output to write code, you may want to keep in mind that I may end up changing the file format considerably still.

Also, "Save As" is indeed implemented... maybe you just haven't updated?
